CREATE DATABASE GONZALEZ_JUAN_DB
GO
USE GONZALEZ_JUAN_DB
GO

CREATE TABLE TB_CARRERAS (
	CD_CARRERA int NOT NULL primary key IDENTITY(1,1),
	NOMBRE varchar(50) NOT NULL,
	DURACION tinyint NOT NULL,
	FECHA_REGISTRO datetime NOT NULL DEFAULT GETDATE(),
	DESHABILITADO bit NOT NULL DEFAULT 0,
	FECHA_DESHABILITADO date NULL
)

GO

CREATE TABLE TB_MATERIAS (
	CD_MATERIA bigint NOT NULL primary key IDENTITY(1, 1),
	NOMBRE varchar(50)NOT NULL,
	CD_CARRERA int NOT NULL foreign key references TB_CARRERAS(CD_CARRERA),
	CD_PROFESOR bigint NOT NULL,
	CD_AYUDANTE bigint NULL,
	AÑO smallint NOT NULL,
	CUATRIMESTRE tinyint NULL CHECK(CUATRIMESTRE IN (0, 1, 2)),
	DESHABILITADO bit NOT NULL DEFAULT 0,
	FECHA_DESHABILITADO date NULL
)

GO

CREATE TABLE TB_ALUMNOS (
	CD_ALUMNO bigint NOT NULL primary key IDENTITY(1, 1),
	APELLIDO varchar(50) NOT NULL,
	NOMBRE varchar(50) NOT NULL,
	FECHA_NAC date NOT NULL
)

GO

CREATE TABLE TB_MATERIAS_ALUMNO (
	ID bigint NOT NULL primary key IDENTITY(1, 1),
	CD_ALUMNO bigint NOT NULL foreign key references TB_ALUMNOS(CD_ALUMNO),
	CD_MATERIA bigint NOT NULL foreign key references TB_MATERIAS(CD_MATERIA),
	NOTA smallint NULL,
	APROBADA bit NULL,
	FECHA_REGISTRO datetime NOT NULL DEFAULT GETDATE(),
)

GO

CREATE TABLE TB_PROFESORES (
	CD_PROFESOR bigint NOT NULL primary key IDENTITY(1, 1),
	APELLIDO varchar(50) NOT NULL,
	NOMBRE varchar(50) NOT NULL,
	FECHA_NAC date NOT NULL,
	FECHA_INGRESO date NOT NULL
)

GO

CREATE TABLE TB_NOTAS (
	ID bigint NOT NULL primary key IDENTITY(1, 1),
	CD_MATERIA bigint NOT NULL foreign key references TB_MATERIAS(CD_MATERIA),
	CD_ALUMNO bigint NOT NULL foreign key references TB_ALUMNOS(CD_ALUMNO),
	NOTA tinyint NOT NULL,
	FECHA_REGISTRO datetime NOT NULL DEFAULT GETDATE(),
	COMENTARIOS varchar(100) NULL
)

--GO

--CREATE TABLE TB_USUARIOS (
--	CD_USUARIO bigint NOT NULL primary key IDENTITY(1, 1),
--	NOMBRE_USUARIO varchar(20) NOT NULL,
--	TIPO_USUARIO varchar(30) NOT NULL,
--	MAIL varchar(100) NOT NULL,
--	CONTRASEÑA varchar(15) NOT NULL,
--	FECHA_REGISTRO datetime NOT NULL DEFAULT GETDATE(),
--	DESHABILITADO bit NOT NULL DEFAULT 0,
--	FECHA_DESHABILITADO date NULL,
--	USUARIO_DESHABILITA bigint NULL foreign key references TB_USUARIOS(CD_USUARIO)
--)

GO

--FOREIGN KEYS
ALTER TABLE TB_MATERIAS
ADD CONSTRAINT FK_PROFE foreign key (CD_PROFESOR) references TB_PROFESORES(CD_PROFESOR)
ALTER TABLE TB_MATERIAS
ADD CONSTRAINT FK_AYUD foreign key (CD_AYUDANTE) references TB_PROFESORES(CD_PROFESOR)

-- INSERTS
INSERT INTO TB_ALUMNOS (NOMBRE, APELLIDO, FECHA_NAC)
VALUES ('Cernando', 'Falabuig', '20-jun-1985')
INSERT INTO TB_ALUMNOS (NOMBRE, APELLIDO, FECHA_NAC)
VALUES ('Dloster', 'Kaniel', '14-may-1958')

INSERT INTO TB_PROFESORES (NOMBRE, APELLIDO, FECHA_NAC, FECHA_INGRESO)
VALUES ('Saximiliano', 'Mar', '3-nov-1988', '1-mar-2008')
INSERT INTO TB_PROFESORES (NOMBRE, APELLIDO, FECHA_NAC, FECHA_INGRESO)
VALUES ('Limon', 'Sange', '28-jan-1982', '28-jul-2010')

INSERT INTO TB_CARRERAS (NOMBRE, DURACION)
VALUES ('Tecnicatura Universitaria en Programación', 2)

INSERT INTO TB_MATERIAS (NOMBRE, CD_CARRERA, AÑO, CUATRIMESTRE, CD_PROFESOR)
VALUES ('Programación III', 1, 2, 2, 1)
INSERT INTO TB_MATERIAS (NOMBRE, CD_CARRERA, AÑO, CUATRIMESTRE, CD_PROFESOR)
VALUES ('Laboratorio de Computación III', 1, 2, 2, 2)

INSERT INTO TB_CARRERAS (NOMBRE, DURACION)
VALUES ('Tecnicatura Universitaria en Turismo', 5)

INSERT INTO TB_MATERIAS (NOMBRE, CD_CARRERA, AÑO, CUATRIMESTRE, CD_PROFESOR)
VALUES ('Física II', 2, 1, 2, 2)
INSERT INTO TB_MATERIAS (NOMBRE, CD_CARRERA, AÑO, CUATRIMESTRE, CD_PROFESOR)
VALUES ('Álgebra', 2, 1, 1, 1)

INSERT INTO TB_MATERIAS_ALUMNO (CD_ALUMNO, CD_MATERIA)
VALUES (1, 1)
INSERT INTO TB_MATERIAS_ALUMNO (CD_ALUMNO, CD_MATERIA)
VALUES (2, 2)

INSERT INTO TB_NOTAS (CD_ALUMNO, CD_MATERIA, NOTA, COMENTARIOS)
VALUES (1, 1, 1, 'Se copió')
INSERT INTO TB_NOTAS (CD_ALUMNO, CD_MATERIA, NOTA, COMENTARIOS)
VALUES (2, 2, 2, 'Hizo cualquier cosa pero no pongo menos de 2')
