USE master
GO
DECLARE @dbname nvarchar(128)
SET @dbname = N'GONZALEZ_JUAN_DB'

IF (EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE ('[' + name + ']' = @dbname 
OR name = @dbname)))
DROP DATABASE GONZALEZ_JUAN_DB

GO

CREATE DATABASE GONZALEZ_JUAN_DB
GO
USE [GONZALEZ_JUAN_DB]
GO
/****** Object:  Table [dbo].[TB_ALUMNOS]    Script Date: 22/6/2019 16:11:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_ALUMNOS](
	[CD_ALUMNO] [int] IDENTITY(1,1) NOT NULL,
	[APELLIDO] [varchar](50) NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[FECHA_NAC] [date] NOT NULL,
	[DESHABILITADO] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CD_ALUMNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_ALUMNOS_COMISIONES]    Script Date: 22/6/2019 16:11:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_ALUMNOS_COMISIONES](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CD_COMISION] [bigint] NOT NULL,
	[CD_ALUMNO] [int] NOT NULL,
	[NOTA_ID] [bigint] NULL,
	[DESHABILITADO] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[CD_COMISION] ASC,
	[CD_ALUMNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_CARRERAS]    Script Date: 22/6/2019 16:11:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_CARRERAS](
	[CD_CARRERA] [smallint] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[NOMBRE_CORTO] [varchar](10) NOT NULL,
	[DURACION] [tinyint] NOT NULL,
	[DESHABILITADO] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CD_CARRERA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_COMISIONES]    Script Date: 22/6/2019 16:11:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_COMISIONES](
	[CD_COMISION] [bigint] IDENTITY(1,1) NOT NULL,
	[CD_MATERIA] [int] NOT NULL,
	[AÑO] [int] NOT NULL,
	[CUATRIMESTRE] [tinyint] NULL,
	[CD_MODALIDAD] [tinyint] NOT NULL,
	[DESHABILITADO] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CD_COMISION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_COMPETENCIAS]    Script Date: 22/6/2019 16:11:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_COMPETENCIAS](
	[CD_COMPETENCIA] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION] [varchar](50) NOT NULL,
	[DESHABILITADO] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CD_COMPETENCIA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_COMPETENCIAS_EXAMENES]    Script Date: 22/6/2019 16:11:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_COMPETENCIAS_EXAMENES](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CD_EXAMEN] [bigint] NOT NULL,
	[CD_COMPETENCIA] [int] NOT NULL,
	[DESHABILITADO] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_ESTADOS_MATERIA]    Script Date: 22/6/2019 16:11:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_ESTADOS_MATERIA](
	[CD_ESTADO] [tinyint] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION] [varchar](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CD_ESTADO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_EXAMENES]    Script Date: 22/6/2019 16:11:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_EXAMENES](
	[CD_EXAMEN] [bigint] IDENTITY(1,1) NOT NULL,
	[CD_COMISION] [bigint] NOT NULL,
	[CD_TIPO] [tinyint] NOT NULL,
	[FECHA] [datetime] NOT NULL,
	[DESHABILITADO] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CD_EXAMEN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_HORARIOS]    Script Date: 22/6/2019 16:11:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_HORARIOS](
	[CD_HORARIO] [int] IDENTITY(1,1) NOT NULL,
	[HORA_INICIO] [time](7) NOT NULL,
	[HORA_FIN] [time](7) NOT NULL,
	[DIA_SEMANA] [tinyint] NOT NULL,
	[DESHABILITADO] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CD_HORARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_HORARIOS_COMISIONES]    Script Date: 22/6/2019 16:11:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_HORARIOS_COMISIONES](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CD_COMISION] [bigint] NOT NULL,
	[CD_HORARIO] [int] NOT NULL,
	[DESHABILITADO] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_INSCRIPCIONES]    Script Date: 22/6/2019 16:11:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_INSCRIPCIONES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AÑO] [int] NOT NULL,
	[CUATRIMESTRE] [tinyint] NOT NULL,
	[FECHA_APERTURA] [date] NOT NULL,
	[FECHA_CIERRE] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[AÑO] ASC,
	[CUATRIMESTRE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_MATERIAS]    Script Date: 22/6/2019 16:11:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_MATERIAS](
	[CD_MATERIA] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[CD_CARRERA] [smallint] NOT NULL,
	[AÑO] [tinyint] NOT NULL,
	[CUATRIMESTRE] [tinyint] NULL,
	[DESHABILITADO] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CD_MATERIA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_MATERIAS_CORRELATIVAS]    Script Date: 22/6/2019 16:11:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_MATERIAS_CORRELATIVAS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CD_MATERIA] [int] NOT NULL,
	[CD_MATERIA_REQUERIDA] [int] NOT NULL,
	[CD_ESTADO_REQUERIDO] [tinyint] NOT NULL,
	[DESHABILITADO] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_MODALIDADES]    Script Date: 22/6/2019 16:11:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_MODALIDADES](
	[CD_MODALIDAD] [tinyint] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION] [varchar](20) NOT NULL,
	[DESHABILITADO] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CD_MODALIDAD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_NOTAS]    Script Date: 22/6/2019 16:11:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_NOTAS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[NOTA] [tinyint] NOT NULL,
	[FECHA_REGISTRO] [datetime] NOT NULL,
	[COMENTARIOS] [varchar](100) NULL,
	[DESHABILITADO] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_PROFESORES]    Script Date: 22/6/2019 16:11:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_PROFESORES](
	[CD_PROFESOR] [int] IDENTITY(1,1) NOT NULL,
	[APELLIDO] [varchar](50) NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[FECHA_NAC] [date] NOT NULL,
	[FECHA_INGRESO] [date] NOT NULL,
	[DESHABILITADO] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CD_PROFESOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_PROFESORES_COMISIONES]    Script Date: 22/6/2019 16:11:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_PROFESORES_COMISIONES](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CD_COMISION] [bigint] NOT NULL,
	[CD_PROFESOR] [int] NOT NULL,
	[CD_ROL_PROFESOR] [tinyint] NOT NULL,
	[DESHABILITADO] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[CD_COMISION] ASC,
	[CD_PROFESOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_ROL_PROFESORES]    Script Date: 22/6/2019 16:11:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_ROL_PROFESORES](
	[CD_ROL_PROFESOR] [tinyint] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION] [varchar](20) NOT NULL,
	[DESHABILITADO] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CD_ROL_PROFESOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TB_TIPO_EXAMEN]    Script Date: 22/6/2019 16:11:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_TIPO_EXAMEN](
	[CD_TIPO] [tinyint] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION] [varchar](20) NOT NULL,
	[DESHABILITADO] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CD_TIPO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TB_ALUMNOS] ADD  DEFAULT ((0)) FOR [DESHABILITADO]
GO
ALTER TABLE [dbo].[TB_ALUMNOS_COMISIONES] ADD  DEFAULT ((0)) FOR [DESHABILITADO]
GO
ALTER TABLE [dbo].[TB_CARRERAS] ADD  DEFAULT ((0)) FOR [DESHABILITADO]
GO
ALTER TABLE [dbo].[TB_COMISIONES] ADD  DEFAULT ((0)) FOR [DESHABILITADO]
GO
ALTER TABLE [dbo].[TB_COMPETENCIAS] ADD  DEFAULT ((0)) FOR [DESHABILITADO]
GO
ALTER TABLE [dbo].[TB_COMPETENCIAS_EXAMENES] ADD  DEFAULT ((0)) FOR [DESHABILITADO]
GO
ALTER TABLE [dbo].[TB_EXAMENES] ADD  DEFAULT ((0)) FOR [DESHABILITADO]
GO
ALTER TABLE [dbo].[TB_HORARIOS] ADD  DEFAULT ((0)) FOR [DESHABILITADO]
GO
ALTER TABLE [dbo].[TB_HORARIOS_COMISIONES] ADD  DEFAULT ((0)) FOR [DESHABILITADO]
GO
ALTER TABLE [dbo].[TB_MATERIAS] ADD  DEFAULT ((0)) FOR [DESHABILITADO]
GO
ALTER TABLE [dbo].[TB_MATERIAS_CORRELATIVAS] ADD  DEFAULT ((0)) FOR [DESHABILITADO]
GO
ALTER TABLE [dbo].[TB_MODALIDADES] ADD  DEFAULT ((0)) FOR [DESHABILITADO]
GO
ALTER TABLE [dbo].[TB_NOTAS] ADD  DEFAULT (getdate()) FOR [FECHA_REGISTRO]
GO
ALTER TABLE [dbo].[TB_NOTAS] ADD  DEFAULT ((0)) FOR [DESHABILITADO]
GO
ALTER TABLE [dbo].[TB_PROFESORES] ADD  DEFAULT ((0)) FOR [DESHABILITADO]
GO
ALTER TABLE [dbo].[TB_PROFESORES_COMISIONES] ADD  DEFAULT ((0)) FOR [DESHABILITADO]
GO
ALTER TABLE [dbo].[TB_ROL_PROFESORES] ADD  DEFAULT ((0)) FOR [DESHABILITADO]
GO
ALTER TABLE [dbo].[TB_TIPO_EXAMEN] ADD  DEFAULT ((0)) FOR [DESHABILITADO]
GO
ALTER TABLE [dbo].[TB_ALUMNOS_COMISIONES]  WITH CHECK ADD FOREIGN KEY([CD_ALUMNO])
REFERENCES [dbo].[TB_ALUMNOS] ([CD_ALUMNO])
GO
ALTER TABLE [dbo].[TB_ALUMNOS_COMISIONES]  WITH CHECK ADD FOREIGN KEY([CD_COMISION])
REFERENCES [dbo].[TB_COMISIONES] ([CD_COMISION])
GO
ALTER TABLE [dbo].[TB_ALUMNOS_COMISIONES]  WITH CHECK ADD FOREIGN KEY([NOTA_ID])
REFERENCES [dbo].[TB_NOTAS] ([ID])
GO
ALTER TABLE [dbo].[TB_COMISIONES]  WITH CHECK ADD FOREIGN KEY([CD_MATERIA])
REFERENCES [dbo].[TB_MATERIAS] ([CD_MATERIA])
GO
ALTER TABLE [dbo].[TB_COMISIONES]  WITH CHECK ADD FOREIGN KEY([CD_MODALIDAD])
REFERENCES [dbo].[TB_MODALIDADES] ([CD_MODALIDAD])
GO
ALTER TABLE [dbo].[TB_COMPETENCIAS_EXAMENES]  WITH CHECK ADD FOREIGN KEY([CD_COMPETENCIA])
REFERENCES [dbo].[TB_COMPETENCIAS] ([CD_COMPETENCIA])
GO
ALTER TABLE [dbo].[TB_COMPETENCIAS_EXAMENES]  WITH CHECK ADD FOREIGN KEY([CD_EXAMEN])
REFERENCES [dbo].[TB_EXAMENES] ([CD_EXAMEN])
GO
ALTER TABLE [dbo].[TB_EXAMENES]  WITH CHECK ADD FOREIGN KEY([CD_COMISION])
REFERENCES [dbo].[TB_COMISIONES] ([CD_COMISION])
GO
ALTER TABLE [dbo].[TB_EXAMENES]  WITH CHECK ADD FOREIGN KEY([CD_TIPO])
REFERENCES [dbo].[TB_TIPO_EXAMEN] ([CD_TIPO])
GO
ALTER TABLE [dbo].[TB_HORARIOS_COMISIONES]  WITH CHECK ADD FOREIGN KEY([CD_COMISION])
REFERENCES [dbo].[TB_COMISIONES] ([CD_COMISION])
GO
ALTER TABLE [dbo].[TB_HORARIOS_COMISIONES]  WITH CHECK ADD FOREIGN KEY([CD_HORARIO])
REFERENCES [dbo].[TB_HORARIOS] ([CD_HORARIO])
GO
ALTER TABLE [dbo].[TB_MATERIAS]  WITH CHECK ADD FOREIGN KEY([CD_CARRERA])
REFERENCES [dbo].[TB_CARRERAS] ([CD_CARRERA])
GO
ALTER TABLE [dbo].[TB_MATERIAS_CORRELATIVAS]  WITH CHECK ADD FOREIGN KEY([CD_ESTADO_REQUERIDO])
REFERENCES [dbo].[TB_ESTADOS_MATERIA] ([CD_ESTADO])
GO
ALTER TABLE [dbo].[TB_MATERIAS_CORRELATIVAS]  WITH CHECK ADD FOREIGN KEY([CD_MATERIA])
REFERENCES [dbo].[TB_MATERIAS] ([CD_MATERIA])
GO
ALTER TABLE [dbo].[TB_MATERIAS_CORRELATIVAS]  WITH CHECK ADD FOREIGN KEY([CD_MATERIA_REQUERIDA])
REFERENCES [dbo].[TB_MATERIAS] ([CD_MATERIA])
GO
ALTER TABLE [dbo].[TB_PROFESORES_COMISIONES]  WITH CHECK ADD FOREIGN KEY([CD_COMISION])
REFERENCES [dbo].[TB_COMISIONES] ([CD_COMISION])
GO
ALTER TABLE [dbo].[TB_PROFESORES_COMISIONES]  WITH CHECK ADD FOREIGN KEY([CD_PROFESOR])
REFERENCES [dbo].[TB_PROFESORES] ([CD_PROFESOR])
GO
ALTER TABLE [dbo].[TB_PROFESORES_COMISIONES]  WITH CHECK ADD FOREIGN KEY([CD_ROL_PROFESOR])
REFERENCES [dbo].[TB_ROL_PROFESORES] ([CD_ROL_PROFESOR])
GO
ALTER TABLE [dbo].[TB_HORARIOS]  WITH CHECK ADD CHECK  (([DIA_SEMANA]>=(0) AND [DIA_SEMANA]<=(6)))
GO
ALTER TABLE [dbo].[TB_INSCRIPCIONES]  WITH CHECK ADD CHECK  (([cuatrimestre]=(2) OR [cuatrimestre]=(1) OR [cuatrimestre]=(0)))
GO
ALTER TABLE [dbo].[TB_INSCRIPCIONES]  WITH CHECK ADD CHECK  (([FECHA_APERTURA]<[FECHA_CIERRE]))
GO
ALTER TABLE [dbo].[TB_MATERIAS]  WITH CHECK ADD CHECK  (([CUATRIMESTRE]=(2) OR [CUATRIMESTRE]=(1) OR [CUATRIMESTRE]=(0)))
GO
ALTER TABLE [dbo].[TB_MATERIAS_CORRELATIVAS]  WITH CHECK ADD CHECK  (([CD_MATERIA]<>[CD_MATERIA_REQUERIDA]))
GO


SET DATEFORMAT 'DMY'
GO
INSERT INTO TB_ALUMNOS([APELLIDO],[NOMBRE],[FECHA_NAC]) 
VALUES('Sanford','Camille','28/09/81'),('Sykes','Patience','13/10/83'),('Poole','Ocean','15/03/83'),('Woodward','Farrah','05/02/95'),('Murphy','Joy','04/06/84'),('Mcpherson','Orla','17/10/88'),('Morton','Veda','10/02/92'),('Mercer','Aline','17/03/98'),('Patterson','Kessie','02/11/81'),('Baxter','Halee','11/01/83');
GO
INSERT INTO TB_PROFESORES([APELLIDO],[NOMBRE],[FECHA_NAC],[FECHA_INGRESO]) 
VALUES('Mann','Hedwig','30/12/85','20/02/11'),('Gates','Omar','30/10/80','09/10/08'),('Beard','Chaney','09/01/84','07/05/10'),('Goodman','Jessica','16/04/97','12/09/08'),('Wilkinson','Rhona','16/04/88','26/10/07'),('Mcintyre','Elaine','21/06/87','11/02/13'),('Chen','Jolie','01/02/83','13/03/15'),('Weaver','Blaze','26/01/82','29/12/11'),('Hull','Dennis','24/10/80','07/08/11'),('Puckett','Madeline','11/10/92','01/06/13');
GO

INSERT INTO TB_CARRERAS (NOMBRE, NOMBRE_CORTO, DURACION)
VALUES ('Tecnicatura Universitaria en Programación', 'TUP', 2), 
	   ('Tecnicatura Universitaria en Sistemas Informáticos', 'TUSI', 1)
GO

INSERT INTO TB_MATERIAS (NOMBRE, CD_CARRERA, AÑO, CUATRIMESTRE)
VALUES ('Sistemas de Procesamiento de Datos', 1, 1, 1), ('Programación I', 1, 1, 1), ('Matemática', 1, 1, 1), ('Inglés I', 1, 1, 1), ('Laboratorio de Computación I', 1, 1, 1), 
	   ('Programación II', 1, 1, 2), ('Estadística', 1, 1, 2), ('Arquitectura y Sistemas Operativos', 1, 1, 2), ('Laboratorio de Computación II', 1, 1, 2), ('Inglés II', 1, 1, 2), ('Metodología de la Investigación', 1, 1, 2),
	   ('Laboratorio de Computación III', 1, 2, 1), ('Organización Empresarial', 1, 2, 1), ('Organización Contable de la Empresa', 1, 2, 1), ('Elementos de Investigación Operativa', 1, 2, 1), ('Programación III', 1, 2, 1), ('Práctica Profesional', 1, 2, 1),
	   ('Legislación', 1, 2, 2), ('Diseño y Administración de Bases de Datos', 1, 2, 2), ('Metodología de Sistemas I', 1, 2, 2), ('Laboratorio de Computación IV', 1, 2, 2)
GO
INSERT INTO TB_MATERIAS (NOMBRE, CD_CARRERA, AÑO, CUATRIMESTRE)
VALUES ('Matemática II', 2, 1, 1), ('Inglés Avanzado I', 2, 1, 1), ('Base de Datos II', 2, 1, 1), ('Programación Avanzada I', 2, 1, 1), ('Laboratorio V', 2, 1, 1), ('Metodología de Sistemas II', 2, 1, 1), ('Redes', 2, 1, 1), ('Práctica Profesional', 2, 1, 1),
	   ('Matemática III', 2, 1, 2), ('Inglés Avanzado II', 2, 1, 2), ('Investigación Operativa II', 2, 1, 2), ('Programación Avanzada II', 2, 1, 2), ('Metodología de Sistemas III', 2, 1, 2), ('Administración y Dirección de Proyectos', 2, 1, 2), ('Seminario', 2, 1, 2)
GO

INSERT INTO TB_ESTADOS_MATERIA (DESCRIPCION)
VALUES ('Aprobada'), ('Regularizada'), ('Cursando'), ('Recursada'), ('Abandonada')
GO
INSERT INTO TB_MODALIDADES (DESCRIPCION)
values ('Presencial'), ('Semi presencial'), ('A distancia')
